### ISSUE TITLE
PIP-1 issues

### ISSUE THREAD

**Issue by b00f** [pactus-project/PIPs#1]
### Proposed Change

The [PIP-1](https://github.com/pactus-project/PIPs/blob/main/PIPs/pip-1.md) is a good starting point for the improvement proposals. However, there are a few areas that could be enhanced to make it more specific to the Pactus platform:

1. The content of PIP-1 appears to be borrowed from [EIP-1](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1.md). While some compatibility is expected, it would be beneficial to discuss the proposal specifically for Pactus.
2. The specification and format of the PIP are not clearly defined.
3. The classification or type of the PIP needs to be discussed.
4. The workflow for submitting and reviewing PIPs is not defined.
5. The license for PIPs is not defined. 

By addressing these points, we can enhance the clarity, specificity, and overall effectiveness of the PIP process for the Pactus platform.

**Comment by Ja7ad** [comment]
Thank you

1. Yes content need to refactor.
3. We can discussed about classification of PIPs
4. Yes not defined
5. License defined https://github.com/pactus-project/PIPs#CC0-1.0-1

**Comment by b00f** [comment]
We should add license in each PIP

**Comment by Ja7ad** [comment]
I speak with Dr. Alahbakhsh for improvement PIP-1
